apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yourls
  template:
    metadata:
      labels:
        app: yourls
    spec:
      containers:
        - name: yourls
          image: yourls:latest
          ports:
            - containerPort: 80
          env:
            - name: YOURLS_SITE
              value: "http://localhost:8080"
            - name: YOURLS_USER
              value: "INSERT_HERE"
            - name: YOURLS_PASS
              value: "INSERT_HERE"
            - name: YOURLS_DB_HOST
              value: "mysql"
            - name: YOURLS_DB_USER
              value: "yourls"
            - name: YOURLS_DB_PASS
              value: "yourpassword"
            - name: YOURLS_DB_NAME
              value: "yourls"
---
apiVersion: v1
kind: Service
metadata:
  name: yourls
spec:
  selector:
    app: yourls
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
