apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yourls
  template:
    metadata:
      labels:
        app: yourls
    spec:
      containers:
        - name: yourls
          image: yourls:latest
          env:
            - name: YOURLS_DB_HOST
              value: mysql
            - name: YOURLS_DB_USER
              value: root
            - name: YOURLS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: YOURLS_DB_NAME
              value: yourls
            - name: YOURLS_SITE
              value: "http://localhost:8080"
            - name: YOURLS_USER
              value: admin
            - name: YOURLS_PASS
              value: password
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yourls
spec:
  selector:
    app: yourls
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
